---
- name: Build and Deploy Docker Image to Kubernetes
  hosts: localhost
  connection: local

  vars: 
    image_name: my-compte-service
    image_tag: "2"
    dockerfile_path: './'
    docker_registry_username: eyaamri
    docker_registry_password: evyAa10123
  vars_files:
    - vault.yml


  tasks:
    - name: Log in to Docker Hub
      community.general.docker_login:
        username: "{{docker_registry_username}}"
        password:  "{{docker_registry_password}}"
            


    - name: Build Docker image
      docker_image:
        build:
          path : "{{dockerfile_path}}"
        name: "{{docker_registry_username}}/{{image_name}}"
        tag: "{{ image_tag }}"
        source: build
        state: present
        

    - name: Push the Docker image to Docker Hub
      docker_image:
        name: "{{ docker_registry_username }}/{{ image_name }}"
        tag: "{{image_tag}}"
        push: yes
        source: local

    - name: Pull Docker image (optional, for verification or on target nodes)
      docker_image:
        name: "{{ docker_registry_username }}/{{ image_name }}"
        tag: "{{image_tag}}"
        source: pull

    - name: Apply Kubernetes Deployment
      kubernetes.core.k8s:
        state: present
        namespace: jenkins
        src: deployment.yaml
        kubeconfig: config # Path to your kubeconfig file

    - name: Apply Kubernetes Service
      kubernetes.core.k8s:
        state: present
        namespace: jenkins
        src: service.yaml
        kubeconfig: config

