---
- name: Build and Deploy Docker Image to Kubernetes
  hosts: localhost
  connection: local

  vars: 
    image_name: my-compte-service
    # image_tag sera surchargé par Jenkins (-e "image_tag=...")
    image_tag: "latest" 
    dockerfile_path: './'
    docker_registry_username: eyaamri
    docker_registry_password: evyAa10123
  vars_files:
    - vault.yml

  tasks:
    - name: Log in to Docker Hub
      community.general.docker_login:
        username: "{{docker_registry_username}}"
        password: "{{docker_registry_password}}"

    - name: Build Docker image
      docker_image:
        build:
          path: "{{dockerfile_path}}"
        name: "{{docker_registry_username}}/{{image_name}}"
        tag: "{{ image_tag }}"
        source: build
        state: present

    - name: Push the Docker image to Docker Hub
      docker_image:
        name: "{{ docker_registry_username }}/{{ image_name }}"
        tag: "{{image_tag}}"
        push: yes
        source: local

    # --- DÉPLOIEMENT KUBERNETES ---

    # Assurons-nous que le namespace existe
    - name: Create namespace if not exists
      kubernetes.core.k8s:
        name: jenkins
        api_version: v1
        kind: Namespace
        state: present
        kubeconfig: config

    - name: Apply Kubernetes Deployment
      kubernetes.core.k8s:
        state: present
        namespace: jenkins
        src: deployment.yaml
        kubeconfig: config
        # Force le redémarrage pour prendre la nouvelle image si le tag est identique (ex: latest)
        force: yes 

    - name: Apply Kubernetes Service
      kubernetes.core.k8s:
        state: present
        namespace: jenkins
        src: service.yaml
        kubeconfig: config

    - name: Apply Prometheus ServiceMonitor
      kubernetes.core.k8s:
        state: present
        namespace: jenkins
        src: servicemonitor.yaml
        kubeconfig: config
      # J'ai retiré ignore_errors: yes car Prometheus est installé maintenant !
