apiVersion: v1
kind: Service
metadata:
  name: my-country-service
  labels:
    app: country-service # Important pour la s√©lection
spec:
  type: NodePort
  selector:
    app: country-service
  ports:
    - name: http          # <--- AJOUT CRUCIAL : Nommer le port
      port: 8080
      targetPort: 8080 
      nodePort: 30015
      protocol: TCP









